export const ACTION_TYPES = {
    QUIZ: 'QUIZ',
    START_QUIZ: 'START_QUIZ',
    NEXT_QUIZ: 'NEXT_ANSWER',
    WRONG_QUIZ: 'WRONG_QUIZ',
    START_TIMER: 'START_TIMER',
    END_TIMER: 'END_TIMER',
    BEST_RESULT: 'BEST_RESULT',
    NEGATIVE_RESULT: 'NEGATIVE_RESULT',
    GET_RESULT: 'GET_RESULT',
    QUIT_QUIZ: 'QUIT_QUIZ,'
}