export const ACTION_TYPES = {
    OPERATION: 'OPERATION',
    NEXT_OPERATION: 'NEXT_OPERATION',
    RIGHT_ANSWER: 'RIGHT_ANSWER',
    NULL_ANSWER: 'NULL_ANSWER',
    WRONG_ANSWER: 'WRONG_ANSWER',
    SHOW_ANSWER: 'SHOW_ANSWER',
    QUIZ: 'QUIZ',
    START_QUIZ: 'START_QUIZ',
    NEXT_QUIZ: 'NEXT_ANSWER',
    WRONG_QUIZ: 'WRONG_QUIZ',
    START_TIMER: 'START_TIMER',
    END_TIMER: 'END_TIMER',
    BEST_RESULT: 'BEST_RESULT',
    NEGATIVE_RESULT: 'NEGATIVE_RESULT',
    RESULTS: 'RESULTS',
    GET_RESULT: 'GET_RESULT',
    // START_PAGE: 'START_PAGE'
}