export const ACTION_TYPES = {
    RIGHT_ANSWER: 'RIGHT_ANSWER',
    NULL_ANSWER: 'NULL_ANSWER',
    WRONG_ANSWER: 'WRONG_ANSWER',
    SHOW_ANSWER: 'SHOW_ANSWER',
    CLEAN_OUT_ANSWER: 'CLEAN_OUT_ANSWER',
}